- Server:
    - Elasticsearch:
        icon: elasticsearch
        href: http://elasticsearch.homelab.local
    - Kibana:
        icon: kibana
        href: http://kibana.homelab.local
    - Neo4j Browser:
        icon: neo4j
        href: http://neo4j.homelab.local
    - Neo4j Bolt:
        icon: neo4j
        href: http://wonko.local:7687
    - Neodash:
        icon: neo4j
        href: http://neodash.homelab.local

- Workflows:
    - Prefect:
        description: Prefect Server
        icon: apache-airflow
        href: http://prefect.homelab.local/dashboard
    - N8N:
        icon: n8n
        href: http://n8n.homelab.local

- LLMs:
    - LibreChat:
        icon: librechat
        href: http://librechat.homelab.local

- OrangePi5B:
    - OpenHAB:
        icon: openhab
        href: http://openhab.homelab.local
    - Portainer:
        icon: portainer
        href: http://portainer.homelab.local
    - Zigbee2MQTT:
        icon: zigbee2mqtt
        href: http://zigbee2mqtt.homelab.local
    - Mosquitto MQTT Broker:
        icon: mqtt
        href: http://mosquitto.homelab.local
    - Rabbit MQ:
        icon: rabbitmq
        href: http://rabbitmq.homelab.local

- Networking:
    - Pi-hole:
        icon: pi-hole
        href: http://pihole.homelab.local
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
    - Traefik:
        icon: traefik
        href: http://traefik.homelab.local
