- Server:
    - Elasticsearch:
        icon: elasticsearch
        href: http://wonko.local:9200
    - Kibana:
        icon: kibana
        href: http://wonko.local:5601
    - Neo4j Browser:
        icon: neo4j
        href: http://wonko.local:7474
    - Neo4j Bolt:
        icon: neo4j
        href: http://wonko.local:7687
    - Neodash:
        icon: neo4j
        href: http://wonko.local:5005

- Workflows:
    - Prefect:
        description: Prefect Server
        icon: apache-airflow
        href: http://wonko.local:4200/dashboard
    - N8N:
        icon: n8n
        href: http://wonko.local:5678/

- LLMs:
    - LibreChat:
        icon: librechat
        href: http://wonko.local:3080/

- OrangePi5B:
    - OpenHAB:
        icon: openhab
        href: http://orangepi5b.local:8080
    - Portainer:
        icon: portainer
        href: https://orangepi5b.local:9443/
    - Zigbee2MQTT:
        icon: zigbee2mqtt
        href: http://orangepi5b.local:8081/
    - Mosquitto MQTT Broker:
        icon: mqtt
        href: http://orangepi5b.local:9002/
    - Rabbit MQ:
        icon: rabbitmq
        href: http://orangepi5b.local:15672/

- Networking:
    - Pi-hole:
        icon: pi-hole
        href: http://orangepi5b.local:8082
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
    - Traefik:
        icon: traefik
        href: http://orangepi5b.local:9080/
