- Server:
    - Elasticsearch:
        icon: elasticsearch
        href: http://elasticsearch.home
    - Kibana:
        icon: kibana
        href: http://kibana.home
    - Neo4j Browser:
        icon: neo4j
        href: http://neo4j.omnidian.home
    - Neo4j Bolt:
        icon: neo4j
        href: http://neo4j.bolt.omnidian.home
    - Neodash:
        icon: neo4j
        href: http://neodash.home

- Workflows:
    - Prefect:
        description: Prefect Server
        icon: apache-airflow
        href: http://prefect.home/dashboard
    - N8N:
        icon: n8n
        href: http://n8n.home

- LLMs:
    - LibreChat:
        icon: librechat
        href: http://librechat.home

- OrangePi5B:
    - OpenHAB:
        icon: openhab
        href: http://openhab.home
    - Portainer:
        icon: portainer
        href: http://portainer.home
    - Zigbee2MQTT:
        icon: zigbee2mqtt
        href: http://zigbee2mqtt.home
    - Mosquitto MQTT Broker:
        icon: mqtt
        href: http://mosquitto.home
    - Rabbit MQ:
        icon: rabbitmq
        href: http://rabbitmq.home

- Networking:
    - Pi-hole:
        icon: pi-hole
        href: http://pihole.home/admin
    - Tailscale:
        icon: tailscale
        href: https://login.tailscale.com/admin/machines
    - Traefik:
        icon: traefik
        href: http://traefik.home
