- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
      # In order to use portainer widget or docker you would have to add in a 
      # label as show in here https://gethomepage.dev/configs/docker/#automatic-service-discovery
      # I don't really like that syntax
      #- portainer:
      #   type: portainer
      #   url: https://orangepi5b.local:9443
      #   env: 3
      #   key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
